apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-game-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-game
  template:
    metadata:
      labels:
        app: python-game
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: python-game
        image: devop93/gameapplication:v1
        ports:
        - containerPort: 3001
