apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-calculator
  template:
    metadata:
      labels:
        app: java-calculator
    spec:
      containers:
      - name: calculator
        image: devop93/java-calculator:v1  # Replace with your Docker Hub username
        ports:
        - containerPort: 9200
